// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	GetServerVersionRequest
	GetServerVersionResponse
	StartDownloadRequest
	StartDownloadResponse
	StopDownloadRequest
	StopDownloadResponse
	GetTorrentRequest
	GetTorrentResponse
	StatusRequest
	LayerDownState
	StatusResponse
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetServerVersionRequest struct {
}

func (m *GetServerVersionRequest) Reset()                    { *m = GetServerVersionRequest{} }
func (m *GetServerVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetServerVersionRequest) ProtoMessage()               {}
func (*GetServerVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetServerVersionResponse struct {
	Major    uint32 `protobuf:"varint,1,opt,name=major" json:"major,omitempty"`
	Minor    uint32 `protobuf:"varint,2,opt,name=minor" json:"minor,omitempty"`
	Patch    uint32 `protobuf:"varint,3,opt,name=patch" json:"patch,omitempty"`
	Revision string `protobuf:"bytes,4,opt,name=revision" json:"revision,omitempty"`
}

func (m *GetServerVersionResponse) Reset()                    { *m = GetServerVersionResponse{} }
func (m *GetServerVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetServerVersionResponse) ProtoMessage()               {}
func (*GetServerVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type StartDownloadRequest struct {
	Source   string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Stdout   string `protobuf:"bytes,2,opt,name=stdout" json:"stdout,omitempty"`
	Stderr   string `protobuf:"bytes,3,opt,name=stderr" json:"stderr,omitempty"`
	Username string `protobuf:"bytes,4,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
}

func (m *StartDownloadRequest) Reset()                    { *m = StartDownloadRequest{} }
func (m *StartDownloadRequest) String() string            { return proto.CompactTextString(m) }
func (*StartDownloadRequest) ProtoMessage()               {}
func (*StartDownloadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StartDownloadResponse struct {
}

func (m *StartDownloadResponse) Reset()                    { *m = StartDownloadResponse{} }
func (m *StartDownloadResponse) String() string            { return proto.CompactTextString(m) }
func (*StartDownloadResponse) ProtoMessage()               {}
func (*StartDownloadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type StopDownloadRequest struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Clean  bool   `protobuf:"varint,2,opt,name=clean" json:"clean,omitempty"`
}

func (m *StopDownloadRequest) Reset()                    { *m = StopDownloadRequest{} }
func (m *StopDownloadRequest) String() string            { return proto.CompactTextString(m) }
func (*StopDownloadRequest) ProtoMessage()               {}
func (*StopDownloadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type StopDownloadResponse struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *StopDownloadResponse) Reset()                    { *m = StopDownloadResponse{} }
func (m *StopDownloadResponse) String() string            { return proto.CompactTextString(m) }
func (*StopDownloadResponse) ProtoMessage()               {}
func (*StopDownloadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GetTorrentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetTorrentRequest) Reset()                    { *m = GetTorrentRequest{} }
func (m *GetTorrentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTorrentRequest) ProtoMessage()               {}
func (*GetTorrentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type GetTorrentResponse struct {
	Torrent []byte `protobuf:"bytes,1,opt,name=torrent,proto3" json:"torrent,omitempty"`
}

func (m *GetTorrentResponse) Reset()                    { *m = GetTorrentResponse{} }
func (m *GetTorrentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTorrentResponse) ProtoMessage()               {}
func (*GetTorrentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type StatusRequest struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type LayerDownState struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	State     string `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Completed int64  `protobuf:"varint,3,opt,name=completed" json:"completed,omitempty"`
	Size      int64  `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Seeding   bool   `protobuf:"varint,5,opt,name=seeding" json:"seeding,omitempty"`
}

func (m *LayerDownState) Reset()                    { *m = LayerDownState{} }
func (m *LayerDownState) String() string            { return proto.CompactTextString(m) }
func (*LayerDownState) ProtoMessage()               {}
func (*LayerDownState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type StatusResponse struct {
	LayerDownStates []*LayerDownState `protobuf:"bytes,1,rep,name=layerDownStates" json:"layerDownStates,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StatusResponse) GetLayerDownStates() []*LayerDownState {
	if m != nil {
		return m.LayerDownStates
	}
	return nil
}

func init() {
	proto.RegisterType((*GetServerVersionRequest)(nil), "types.GetServerVersionRequest")
	proto.RegisterType((*GetServerVersionResponse)(nil), "types.GetServerVersionResponse")
	proto.RegisterType((*StartDownloadRequest)(nil), "types.StartDownloadRequest")
	proto.RegisterType((*StartDownloadResponse)(nil), "types.StartDownloadResponse")
	proto.RegisterType((*StopDownloadRequest)(nil), "types.StopDownloadRequest")
	proto.RegisterType((*StopDownloadResponse)(nil), "types.StopDownloadResponse")
	proto.RegisterType((*GetTorrentRequest)(nil), "types.GetTorrentRequest")
	proto.RegisterType((*GetTorrentResponse)(nil), "types.GetTorrentResponse")
	proto.RegisterType((*StatusRequest)(nil), "types.StatusRequest")
	proto.RegisterType((*LayerDownState)(nil), "types.LayerDownState")
	proto.RegisterType((*StatusResponse)(nil), "types.StatusResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for API service

type APIClient interface {
	GetServerVersion(ctx context.Context, in *GetServerVersionRequest, opts ...grpc.CallOption) (*GetServerVersionResponse, error)
	StartDownload(ctx context.Context, in *StartDownloadRequest, opts ...grpc.CallOption) (*StartDownloadResponse, error)
	StopDownload(ctx context.Context, in *StopDownloadRequest, opts ...grpc.CallOption) (*StopDownloadResponse, error)
	GetTorrent(ctx context.Context, in *GetTorrentRequest, opts ...grpc.CallOption) (*GetTorrentResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetServerVersion(ctx context.Context, in *GetServerVersionRequest, opts ...grpc.CallOption) (*GetServerVersionResponse, error) {
	out := new(GetServerVersionResponse)
	err := grpc.Invoke(ctx, "/types.API/GetServerVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) StartDownload(ctx context.Context, in *StartDownloadRequest, opts ...grpc.CallOption) (*StartDownloadResponse, error) {
	out := new(StartDownloadResponse)
	err := grpc.Invoke(ctx, "/types.API/StartDownload", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) StopDownload(ctx context.Context, in *StopDownloadRequest, opts ...grpc.CallOption) (*StopDownloadResponse, error) {
	out := new(StopDownloadResponse)
	err := grpc.Invoke(ctx, "/types.API/StopDownload", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetTorrent(ctx context.Context, in *GetTorrentRequest, opts ...grpc.CallOption) (*GetTorrentResponse, error) {
	out := new(GetTorrentResponse)
	err := grpc.Invoke(ctx, "/types.API/GetTorrent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/types.API/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	GetServerVersion(context.Context, *GetServerVersionRequest) (*GetServerVersionResponse, error)
	StartDownload(context.Context, *StartDownloadRequest) (*StartDownloadResponse, error)
	StopDownload(context.Context, *StopDownloadRequest) (*StopDownloadResponse, error)
	GetTorrent(context.Context, *GetTorrentRequest) (*GetTorrentResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_GetServerVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetServerVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.API/GetServerVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetServerVersion(ctx, req.(*GetServerVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_StartDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).StartDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.API/StartDownload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).StartDownload(ctx, req.(*StartDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_StopDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).StopDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.API/StopDownload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).StopDownload(ctx, req.(*StopDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.API/GetTorrent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetTorrent(ctx, req.(*GetTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.API/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerVersion",
			Handler:    _API_GetServerVersion_Handler,
		},
		{
			MethodName: "StartDownload",
			Handler:    _API_StartDownload_Handler,
		},
		{
			MethodName: "StopDownload",
			Handler:    _API_StopDownload_Handler,
		},
		{
			MethodName: "GetTorrent",
			Handler:    _API_GetTorrent_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _API_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x73, 0xd3, 0x30,
	0x10, 0x25, 0x71, 0x13, 0x92, 0xa5, 0x0d, 0x45, 0x24, 0xd4, 0x75, 0x3b, 0xc0, 0x88, 0x03, 0x3d,
	0xe5, 0x50, 0x0e, 0x1c, 0x19, 0xa6, 0xcc, 0x30, 0x9d, 0xe9, 0x01, 0x14, 0xe0, 0x2e, 0xe2, 0x1d,
	0x30, 0x93, 0x58, 0x46, 0x92, 0x5b, 0xca, 0x91, 0x1f, 0xc1, 0x1f, 0xe5, 0x0f, 0xa0, 0x2f, 0xdb,
	0x89, 0xeb, 0x0e, 0xdc, 0xf4, 0xde, 0x4a, 0xbb, 0x6f, 0x77, 0x9f, 0x0d, 0x63, 0x5e, 0x64, 0xf3,
	0x42, 0x0a, 0x2d, 0xc8, 0x40, 0x5f, 0x17, 0xa8, 0xe8, 0x21, 0x1c, 0xbc, 0x45, 0xbd, 0x40, 0x79,
	0x89, 0xf2, 0x13, 0x4a, 0x95, 0x89, 0x9c, 0xe1, 0xf7, 0x12, 0x95, 0xa6, 0x3f, 0x20, 0xbe, 0x19,
	0x52, 0x85, 0xc8, 0x15, 0x92, 0x29, 0x0c, 0xd6, 0xfc, 0x9b, 0x90, 0x71, 0xef, 0x69, 0xef, 0x64,
	0x8f, 0x79, 0xe0, 0xd8, 0x2c, 0x37, 0x6c, 0x3f, 0xb0, 0x16, 0x58, 0xb6, 0xe0, 0x7a, 0xf9, 0x35,
	0x8e, 0x3c, 0xeb, 0x00, 0x49, 0x60, 0x24, 0xf1, 0x32, 0xb3, 0x59, 0xe3, 0x1d, 0x13, 0x18, 0xb3,
	0x1a, 0xd3, 0xdf, 0x3d, 0x98, 0x2e, 0x34, 0x97, 0xfa, 0x8d, 0xb8, 0xca, 0x57, 0x82, 0xa7, 0x41,
	0x12, 0x79, 0x04, 0x43, 0x25, 0x4a, 0xb9, 0x44, 0x57, 0x77, 0xcc, 0x02, 0x72, 0xbc, 0x4e, 0x45,
	0xa9, 0x5d, 0x65, 0xcb, 0x3b, 0x14, 0x78, 0x94, 0xd2, 0xd5, 0xf6, 0xbc, 0x41, 0xb6, 0x78, 0xa9,
	0x50, 0xe6, 0x7c, 0x8d, 0x55, 0xf1, 0x0a, 0xdb, 0x58, 0xc1, 0x95, 0xba, 0x12, 0x32, 0x8d, 0x07,
	0x3e, 0x56, 0x61, 0x7a, 0x00, 0xb3, 0x96, 0x2e, 0x3f, 0x0f, 0x7a, 0x06, 0x0f, 0x17, 0x5a, 0x14,
	0xff, 0xab, 0xd7, 0x8c, 0x64, 0xb9, 0x42, 0x9e, 0x3b, 0xb9, 0x23, 0xe6, 0x01, 0x3d, 0xb1, 0x5d,
	0x6f, 0x26, 0x09, 0xc3, 0xde, 0x87, 0x28, 0x4b, 0x95, 0x49, 0x11, 0x99, 0x14, 0xf6, 0x48, 0x9f,
	0xc1, 0x03, 0xb3, 0x9a, 0x0f, 0x42, 0x4a, 0xcc, 0x75, 0x55, 0x6c, 0x02, 0xfd, 0x2c, 0x0d, 0x85,
	0xcc, 0x89, 0xce, 0x81, 0x6c, 0x5e, 0x0a, 0xc9, 0x62, 0xb8, 0xab, 0x3d, 0xe5, 0xae, 0xee, 0xb2,
	0x0a, 0xd2, 0xe7, 0xb0, 0x67, 0x9a, 0xd3, 0xa5, 0xfa, 0x87, 0x7a, 0xfa, 0xab, 0x07, 0x93, 0x0b,
	0x7e, 0x8d, 0xd2, 0x2a, 0xb5, 0x4f, 0xb0, 0x5d, 0xdb, 0x36, 0xa8, 0x6c, 0x20, 0xec, 0xc3, 0x03,
	0x72, 0x0c, 0xe3, 0xa5, 0x58, 0x17, 0x2b, 0xd4, 0x98, 0xba, 0x8d, 0x44, 0xac, 0x21, 0x08, 0x81,
	0x1d, 0x95, 0xfd, 0xf4, 0x0b, 0x89, 0x98, 0x3b, 0x5b, 0xb5, 0x0a, 0x31, 0xcd, 0xf2, 0x2f, 0x6e,
	0x17, 0x23, 0x56, 0x41, 0xfa, 0x1e, 0x26, 0x95, 0xda, 0xd0, 0xd9, 0x2b, 0xb8, 0xbf, 0xda, 0x52,
	0xe5, 0x47, 0x76, 0xef, 0x74, 0x36, 0x77, 0x5e, 0x9f, 0x6f, 0x6b, 0x66, 0xed, 0xdb, 0xa7, 0x7f,
	0xfa, 0x10, 0xbd, 0x7e, 0x77, 0x4e, 0x3e, 0xc2, 0x7e, 0xdb, 0xf8, 0xe4, 0x71, 0xc8, 0x71, 0xcb,
	0xc7, 0x92, 0x3c, 0xb9, 0x35, 0x1e, 0x1c, 0x72, 0x87, 0x5c, 0xb8, 0xf9, 0x36, 0xe6, 0x21, 0x47,
	0xe1, 0x4d, 0x97, 0xd5, 0x93, 0xe3, 0xee, 0x60, 0x9d, 0xed, 0x1c, 0x76, 0x37, 0xcd, 0x42, 0x92,
	0xfa, 0xfe, 0x0d, 0x1b, 0x26, 0x47, 0x9d, 0xb1, 0x3a, 0xd5, 0x19, 0x40, 0x63, 0x14, 0x12, 0x37,
	0x9d, 0x6c, 0x1b, 0x2c, 0x39, 0xec, 0x88, 0xd4, 0x49, 0x5e, 0xc2, 0xd0, 0xef, 0x83, 0x4c, 0x1b,
	0xe5, 0x8d, 0x99, 0x92, 0x59, 0x8b, 0xad, 0x1e, 0x7e, 0x1e, 0xba, 0xff, 0xd1, 0x8b, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x0d, 0xb0, 0x4b, 0x1b, 0x9c, 0x04, 0x00, 0x00,
}
